- uri: /api/v1/product/{product_id}
  act: delete
  alias: 删除Product
  table: product
- uri: /api/v1/product/{product_id}
  act: put
  alias: 修改Product
  table: product
- uri: /api/v2/milestone/{milestone_id}
  act: put
  alias: 修改Milestone
  table: milestone
- uri: /api/v2/milestone/{milestone_id}
  act: delete
  alias: 删除Milestone
  table: milestone
- uri: /api/v1/pmachine/{pmachine_id}
  act: delete
  alias: 删除Pmachine
  table: pmachine
- uri: /api/v1/pmachine/{pmachine_id}
  act: put
  alias: 修改Pmachine
  table: pmachine
- uri: /api/v1/pmachine/{pmachine_id}/power
  act: put
  alias: 修改Pmachine上下电
  table: pmachine
- uri: /api/v1/pmachine/{pmachine_id}/install
  act: put
  alias: 安装Pmachine
  table: pmachine
- uri: /api/v1/pmachine/{pmachine_id}/delay
  act: put
  alias: 修改Pmachine占用时间
  table: pmachine
- uri: /api/v1/pmachine/{pmachine_id}/occupy
  act: put
  alias: 占用Pmachine
  table: pmachine
- uri: /api/v1/pmachine/{pmachine_id}/release
  act: put
  alias: 释放Pmachine
  table: pmachine
- uri: /api/v1/pmachine/{pmachine_id}/ssh
  act: put
  alias: 修改Pmachine的ssh密码
  table: pmachine
- uri: /api/v1/pmachine/{pmachine_id}/bmc
  act: put
  alias: 修改Pmachine的bmc密码
  table: pmachine
- uri: /api/v1/machine-group/{machine_group_id}
  act: delete
  alias: 删除Machine_Group
  table: machine_group
- uri: /api/v1/machine-group/{machine_group_id}
  act: put
  alias: 修改Machine_Group
  table: machine-group
- uri: /api/v1/vmachine/{vmachine_id}
  act: delete
  alias: 删除Vmachine
  table: vmachine
- uri: /api/v1/vmachine/{vmachine_id}
  act: put
  alias: 修改Vmachine
  table: vmachine
- uri: /api/v1/vmachine/{vmachine_id}/ipaddr
  act: put
  alias: 修改Vmachine的ip地址
  table: vmachine
- uri: /api/v1/template/{template_id}
  act: delete
  alias: 删除Template
  table: template
- uri: /api/v1/template/{template_id}
  act: put
  alias: 修改Template
  table: template
- uri: /api/v1/framework/{framework_id}
  act: delete
  alias: 删除Framework
  table: framework
- uri: /api/v1/framework/{framework_id}
  act: put
  alias: 修改Framework
  table: framework
- uri: /api/v1/git-repo/{git_repo_id}
  act: delete
  alias: 删除GitRepo
  table: git_repo
- uri: /api/v1/git-repo/{git_repo_id}
  act: put
  alias: 修改GitRepo
  table: git_repo
- uri:  /api/v1/case/commit/{commit_id}
  act: put
  alias: 修改casecommit
  table: commit
- uri:  /api/v1/case/commit/{commit_id}
  act: get
  alias: 查询casecommit
  table: commit
- uri:  /api/v1/case/commit/{commit_id}
  act: delete
  alias: 删除casecommit
  table: commit
