- alias: 管理员获取组织cla信息
  uri: /api/v1/admin/org
  act: get
- alias: 管理员注册新组织
  uri: /api/v1/admin/org
  act: post
- alias: 管理员更新组织信息
  uri: /api/v1/admin/org
  act: put
- alias: 创建用户组
  uri: /api/v1/groups
  act: post
- alias: 获取当前用户所属的用户组
  uri: /api/v1/groups
  act: get
- alias: 编辑用户组
  uri: /api/v1/groups/{group_id}
  act: put
- alias: 获取某一用户组下的所有用户
  uri: /api/v1/groups/{group_id}/users
  act: get
- alias: 添加用户组成员
  uri: /api/v1/groups/{group_id}/users
  act: post
- alias: 编辑用户组的用户状态
  uri: /api/v1/groups/{group_id}/users
  act: put
- alias: 获取个人消息列表
  uri: /api/v1/msg
  act: get
- alias: 消息置为已读
  uri: /api/v1/msg/batch
  act: put
- alias: 验证cla并绑定组织和用户的关系
  uri: /api/v1/org/{org_id}/cla
  act: post
- alias: 获取组织下人员信息
  uri: /api/v1/org/{org_id}/users
  act: get
- alias: 获取组织下团队信息
  uri: /api/v1/org/{org_id}/groups
  act: get
- alias: 获取所有组织信息
  uri: /api/v1/orgs/all
  act: get
- alias: 获取用户组下所有用户
  uri: /api/v1/users
  act: get
- alias: 用户注册
  uri: /api/v1/users/{gitee_id}
  act: post
- alias: 更新用户信息
  uri: /api/v1/users/{gitee_id}
  act: put
- alias: 获取用户信息
  uri: /api/v1/users/{gitee_id}
  act: get
- alias: 切换当前组织
  uri: /api/v1/users/org/{org_id}
  act: put
- alias: 登出
  uri: /api/v1/logout
  act: delete
- alias: 用户加入用户组
  uri: /api/v1/users/groups/{group_id}
  act: put
- alias: 获取个人任务信息
  uri: /api/v1/user/task/info
  act: post
- alias: 获取个人虚拟机、物理机信息
  uri: /api/v1/user/machine/info
  act: post
- alias: 获取泳道信息
  uri: /api/v1/task/status
  act: get
- alias: 添加新泳道
  uri: /api/v1/task/status
  act: post
- alias: 删除泳道
  uri: /api/v1/task/status/{status_id}
  act: delete
- alias: 修改泳道名
  uri: /api/v1/task/status/{status_id}
  act: put
- alias: 泳道顺序拖动修改
  uri: /api/v1/task/status/order
  act: put
- alias: 获取任务信息(全部)
  uri: /api/v1/tasks
  act: get
- alias: 创建任务
  uri: /api/v1/tasks
  act: post
- alias: 获取任务信息（单个）
  uri: /api/v1/tasks/{task_id}
  act: get
- alias: 编辑任务信息
  uri: /api/v1/tasks/{task_id}
  act: put
- alias: 删除任务
  uri: /api/v1/tasks/{task_id}
  act: delete
- alias: 获取任务协助者信息
  uri: /api/v1/tasks/{task_id}/participants
  act: get
- alias: 编辑任务协助者信息
  uri: /api/v1/tasks/{task_id}/participants
  act: put
- alias: 获取当前组织中的所有协助者
  uri: /api/v1/tasks/participants
  act: get
- alias: 获取任务评论
  uri: /api/v1/tasks/{task_id}/comment
  act: get
- alias: 删除任务评论
  uri: /api/v1/tasks/{task_id}/comment
  act: delete
- alias: 获取回收站信息
  uri: /api/v1/tasks/recycle-bin
  act: get
- alias: 获取任务的关联任务
  uri: /api/v1/tasks/{task_id}/family
  act: get
- alias: 关联父/子任务
  uri: /api/v1/tasks/{task_id}/family
  act: post
- alias: 解除关联父/子任务
  uri: /api/v1/tasks/{task_id}/family
  act: delete
- alias: 获取任务报告
  uri: /api/v1/tasks/{task_id}/reports
  act: get
- alias: 编辑任务报告
  uri: /api/v1/tasks/{task_id}/reports
  act: put
- alias: 任务新增关联用例
  uri: /api/v1/tasks/{task_id}/milestones/{milestone_id}/cases
  act: post
- alias: 删除任务关联用例
  uri: /api/v1/tasks/{task_id}/milestones/{milestone_id}/cases
  act: delete
- alias: 给子任务分配测试用例
  uri: /api/v1/tasks/{task_id}/milestones/{milestone_id}/cases
  act: put
- alias: 获取任务关联用例
  uri: /api/v1/tasks/{task_id}/cases
  act: get
- alias: 获取任务用例结果
  uri: /api/v1/tasks/{task_id}/cases/result
  act: get
- alias: 获取统计页面数据
  uri: /api/v1/task/count/total
  act: get
- alias: 更新手动用例状态
  uri: /api/v1/task/{task_id}/milestones/{taskmilestone_id}/cases/{case_id}
  act: put
- alias: 获取分配模板
  uri: /api/v1/tasks/distribute-templates
  act: get
- alias: 删除分配模板
  uri: /api/v1/tasks/distribute-templates/{template_id}
  act: delete
- alias: 修改分配模板名
  uri: /api/v1/tasks/distribute-templates/{template_id}
  act: put
- alias: 新增子模版
  uri: /api/v1/tasks/distribute-templates/{template_id}/types
  act: post
- alias: 获取子模版信息
  uri: /api/v1/tasks/distribute-templates/suites
  act: get
- alias: 修改子模版
  uri: /api/v1/tasks/distribute-templates/types/{type_id}
  act: put
- alias: 删除子模版
  uri: /api/v1/tasks/distribute-templates/types/{type_id}
  act: delete
- alias: 按照模板分配用例
  uri: /api/v1/tasks/{task_id}/distribute-templates/{template_id}
  act: put
- alias: 批量删除任务
  uri: /api/v1/tasks/list
  act: put
- alias: 根据单测试用例获取唯一关联任务
  uri: /api/v1/case/{case_id}/task
  act: get
- alias: 获取所有角色
  uri: /api/v1/role
  act: get
- alias: 创建角色
  uri: /api/v1/role
  act: post
- alias: 编辑角色
  uri: /api/v1/role/{role_id}
  act: put
- alias: 删除角色
  uri: /api/v1/role/{role_id}
  act: delete
- alias: 获取角色信息
  uri: /api/v1/role/{role_id}
  act: get
- alias: 获取某种类型下所有角色
  uri: /api/v1/role/default
  act: get
- alias: 获取scope数据
  uri: /api/v1/scope
  act: get
- alias: 创建scope
  uri: /api/v1/scope
  act: post
- alias: 编辑scope
  uri: /api/v1/scope/{scope_id}
  act: put
- alias: 删除scope
  uri: /api/v1/scope/{scope_id}
  act: delete
- alias: 用户-公共角色绑定
  uri: /api/v1/user-role
  act: post
- alias: 用户-公共角色解绑
  uri: /api/v1/user-role
  act: delete
- alias: 用户-组织角色绑定
  uri: /api/v1/user-role/org/{org_id}
  act: post
- alias: 用户-组织角色解绑
  uri: /api/v1/user-role/org/{org_id}
  act: delete
- alias: 用户-团队角色绑定
  uri: /api/v1/user-role/group/{group_id}
  act: post
- alias: 用户-团队角色解绑
  uri: /api/v1/user-role/group/{group_id}
  act: delete
- alias: scope-公共角色绑定
  uri: /api/v1/scope-role
  act: post
- alias: scope-公共角色解绑
  uri: /api/v1/scope-role
  act: delete
- alias: scope-组织角色绑定
  uri: /api/v1/scope-role/org/{org_id}
  act: post
- alias: scope-组织角色解绑
  uri: /api/v1/scope-role/org/{org_id}
  act: delete
- alias: scope-团队角色绑定
  uri: /api/v1/scope-role/group/{group_id}
  act: post
- alias: scope-团队角色解绑
  uri: /api/v1/scope-role/group/{group_id}
  act: delete
